from __future__ import annotations

# Campaign drone buddy — one life, 5 HP, deploys from holo shop.
DRONE_WINGMAN_SHOP_PRICE = 20
DRONE_WINGMAN_HITS_MAX = 5
DRONE_HITS_MAX = DRONE_WINGMAN_HITS_MAX

# Combat — rapid fire with overheat lockout.
DRONE_FIRE_INTERVAL = 0.32
DRONE_HEAT_PER_SHOT = 0.13
DRONE_HEAT_DECAY = 0.28
DRONE_OVERHEAT_COOLDOWN = 3.4

# Flight — tighter escort than L4 friendlies.
DRONE_THRUST = 292.0
DRONE_MAX_SPEED = 118.0
DRONE_CATCH_UP_SPEED = 142.0
DRONE_TURN_RATE = 6.35
DRONE_ENGAGE_RANGE = 560.0
DRONE_MIN_RANGE = 52.0
DRONE_FORMATION_TRAIL = 38.0
DRONE_FORMATION_LATERAL = 22.0
DRONE_CATCH_UP_RADIUS = 220.0

# Asteroid awareness — dodge, self-defense fire, guard player.
DRONE_ASTEROID_ENGAGE_RANGE = 380.0
DRONE_ASTEROID_PLAYER_GUARD_RANGE = 320.0
DRONE_ASTEROID_AVOID_RADIUS = 148.0
DRONE_ASTEROID_PANIC_GAP = 52.0
DRONE_ASTEROID_AVOID_THRUST = 420.0
DRONE_ASTEROID_MIN_FIRE_RANGE = 28.0
DRONE_ASTEROID_QUERY_RADIUS = 420.0
