from __future__ import annotations

# Campaign drone buddy — one life, 5 HP, deploys from holo shop.
DRONE_WINGMAN_SHOP_PRICE = 20
DRONE_WINGMAN_HITS_MAX = 5
DRONE_ARMORED_HITS_MAX = 8
DRONE_HITS_MAX = DRONE_WINGMAN_HITS_MAX

# Flight — tighter escort than L4 friendlies; high agility for dodge-first AI.
DRONE_THRUST = 348.0
DRONE_MAX_SPEED = 142.0
DRONE_CATCH_UP_SPEED = 172.0
DRONE_TURN_RATE = 8.4
DRONE_ENGAGE_RANGE = 620.0
DRONE_SQUID_ENGAGE_RANGE = 700.0
DRONE_MIN_RANGE = 48.0
DRONE_KITE_RANGE = 210.0
DRONE_SQUID_KITE_RANGE = 250.0
DRONE_FORMATION_TRAIL = 38.0
DRONE_FORMATION_LATERAL = 22.0
DRONE_CATCH_UP_RADIUS = 220.0

# Combat — rapid fire with overheat lockout; faster vs squids (3 body hits).
DRONE_FIRE_INTERVAL = 0.28
DRONE_SQUID_FIRE_INTERVAL = 0.22
DRONE_HEAT_PER_SHOT = 0.11
DRONE_HEAT_DECAY = 0.32
DRONE_OVERHEAT_COOLDOWN = 2.8

# Hazard awareness — enemies, bolts, rocks.
DRONE_ENEMY_AVOID_RADIUS = 210.0
DRONE_SQUID_PANIC_RADIUS = 128.0
DRONE_ENEMY_AVOID_THRUST = 540.0
DRONE_PROJECTILE_DODGE_RADIUS = 132.0
DRONE_PROJECTILE_DODGE_THRUST = 480.0
DRONE_HIT_INVULN = 0.48
DRONE_ASTEROID_ENGAGE_RANGE = 380.0
DRONE_ASTEROID_PLAYER_GUARD_RANGE = 320.0
DRONE_ASTEROID_AVOID_RADIUS = 148.0
DRONE_ASTEROID_PANIC_GAP = 52.0
DRONE_ASTEROID_AVOID_THRUST = 420.0
DRONE_ASTEROID_MIN_FIRE_RANGE = 28.0
DRONE_ASTEROID_QUERY_RADIUS = 420.0
