from __future__ import annotations

# Weapon doctrine — exclusive shop branch (one pick per campaign).
WEAPON_DOCTRINE_PRICE = 22
WEAPON_ADVANCED_PRICE = 20

# Gatling rigging — one-time modest fire-rate boost (was stackable compounding).
RAPID_FIRE_COOLDOWN_MULT = 0.82
PLAYER_WEAPON_RAPID_FIRE_HEAT_MULT = 1.12

# Player weapon overheat — slow ramp (~2.5s to 45%, ~6.5s to lockout on full auto).
# Global scaler on all heat buildup (per-shot, simmer, escalation). 1.0 = baseline.
PLAYER_WEAPON_HEAT_GAIN_MULT = 0.78
PLAYER_WEAPON_HEAT_PER_SHOT_DEFAULT = 0.023
PLAYER_WEAPON_HEAT_PER_SHOT_LASER = 0.019
PLAYER_WEAPON_HEAT_PER_SHOT_SHOTGUN = 0.032
PLAYER_WEAPON_HEAT_PER_SHOT_SHOTGUN_ADV = 0.038
PLAYER_WEAPON_HEAT_PER_SHOT_EXPLOSIVE = 0.029
PLAYER_WEAPON_HEAT_DECAY_BASE = 0.28
PLAYER_WEAPON_HEAT_DECAY_HEAT_POWER = 2.1
PLAYER_WEAPON_HEAT_DECAY_HEAT_SCALE = 2.85
PLAYER_WEAPON_HEAT_SIMMER_BASE = 0.067
PLAYER_WEAPON_HEAT_SIMMER_HEAT_SCALE = 0.15
PLAYER_WEAPON_HEAT_ESCALATION_START = 0.32
PLAYER_WEAPON_HEAT_ESCALATION_POWER = 1.35
PLAYER_WEAPON_HEAT_ESCALATION_SCALE = 1.20
PLAYER_WEAPON_HEAT_SOFT_START = 0.22
PLAYER_WEAPON_HEAT_SOFT_TIER_1 = 0.55
PLAYER_WEAPON_HEAT_SOFT_TIER_2 = 0.70
PLAYER_WEAPON_HEAT_SOFT_TIER_3 = 0.85
PLAYER_WEAPON_HEAT_SOFT_MAX_MULT = 10.0
PLAYER_WEAPON_OVERHEAT_COOLDOWN = 1.65

# Phase Lance (laser)
LASER_PIERCE_COUNT = 6
LASER_PROJECTILE_RADIUS = 3.2
LASER_SPEED_MULT = 1.08
LASER_TTL = 2.6

# Prismatic Overcharge (laser advanced)
LASER_ADV_PIERCE_COUNT = 9
LASER_ADV_PROJECTILE_RADIUS = 3.6
LASER_ADV_SPEED_MULT = 1.18

# Scatter Cannon (shotgun)
SHOTGUN_PELLET_COUNT = 2
SHOTGUN_SPREAD_RAD = 0.032
SHOTGUN_PROJECTILE_RADIUS = 3.6

# Triple Tap (shotgun advanced) — outer pair spread, center bolt straight
SHOTGUN_ADV_PELLET_COUNT = 3
SHOTGUN_ADV_SIDE_SPREAD_RAD = 0.028

# Nova Shell (explosive)
EXPLOSIVE_SPEED_MULT = 0.62
EXPLOSIVE_COOLDOWN_MULT = 1.38
EXPLOSIVE_BLAST_RADIUS = 54.0
EXPLOSIVE_PROJECTILE_RADIUS = 6.5
EXPLOSIVE_TTL = 2.8

# Supernova Shell (explosive advanced)
EXPLOSIVE_ADV_SPEED_MULT = 0.82
EXPLOSIVE_ADV_COOLDOWN_MULT = 1.22
EXPLOSIVE_ADV_BLAST_RADIUS = 72.0
